### ISSUE TITLE
When I run the timer, an unknown number appears and then disappears.

### ISSUE THREAD

**Issue by synstin** [farhanfadila1717/slide_countdown#53]
I set it up so that a 5 second timer starts when the button is clicked.
In version 1.2.1, when I click the button, an unknown number, 93, appears and then disappears.
In the 0.6.0 version, that number does not appear.

https://github.com/farhanfadila1717/slide_countdown/assets/106897491/784531dd-3495-4947-ac2b-9bd88db9184d
https://github.com/farhanfadila1717/slide_countdown/assets/106897491/7d194638-adbb-476e-8362-495e3731b84d

**Comment by synstin** [comment]
@farhanfadila1717 

Using version 1.2.2 fixed the unknown numbers, thank you.

But when the first number is sliding, the animation is not playing.
For example, if I set a timer for 5 seconds, 
I get 5 -- no animation --> 4 -> 3 -> 2 -> 1

**Comment by farhanfadila1717** [comment]
@synstin checkout the lastest version, i have refacor the `RawDigitItem` widget.

**Comment by synstin** [comment]
@farhanfadila1717 
Thank you so much. But, This has been fixed, but a new error occurs.
```
flutter: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 527 pos 7: '_ticker != null': AnimationController.animateTo() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
flutter: 
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      AnimationController.animateTo (package:flutter/src/animation/animation_controller.dart:527:7)
#3      _RawDigitItemState.playHalfControllerOne (package:slide_countdown/src/widgets/raw_digit_item.dart:134:26)
```

And slideAnimationDuration option and the curve option are gone.
Is it not possible to customize slideAnimationDuration and curve now?
The sliding speed is too slow.
I'm really sorry for the continued demand.

**Comment by farhanfadila1717** [comment]
@synstin whoop it's seems i forgot check the widget still mounted or disposing. i've tried to fix this, checkout the latest version. 

thanks for using and reporting issue in my OS, i really appreciate it 🍻

**Comment by farhanfadila1717** [comment]
@synstin yes it's true, i decided to remove `slide Countdown duration` and `curve`.

**Comment by farhanfadila1717** [comment]
Hi @synstin  sorry for late reply, now you can custom slide animation duration. Please check out [slide_countdown 2.0.1-dev+1 ](https://pub.dev/packages/slide_countdown/versions/2.0.1-dev+1)

**Comment by synstin** [comment]
@farhanfadila1717 Thank you, but is it possible to change the animation curves? I was able to in the previous version.

**Comment by synstin** [comment]
@farhanfadila1717 
Setting slideAnimationDuration has no effect.

**Comment by farhanfadila1717** [comment]
@synstin I have fixed it and published it in the latest dev version. checkout https://pub.dev/packages/slide_countdown/versions/2.0.1-dev+2

**Comment by nickolasdeluca** [comment]
I ran into a similar issue lately and I believe it has been fixed in PR #83
